@startuml
hide circle
skinparam classAttributeIconSize 0

package "commands" {
    abstract class "{abstract} \n Command" {
        + execute(): CommandResult
        + execute(catalogue: Catalogue<?>): CommandResult
    }

    class AddCommand
    class BackCommand
    class ByeCommand
    class CookableRecipesCommand
    class CookRecipeCommand
    class DeleteCommand
    class EditRecipeCommand
    class FindCommand
    class GoToCommand
    class ListCommand
    class UpdateCommand
    class ListCommandsCommand

    "{abstract} \n Command" <|-- AddCommand
    "{abstract} \n Command" <|--- BackCommand
    "{abstract} \n Command" <|-- ByeCommand
    "{abstract} \n Command" <|--- CookableRecipesCommand
    "{abstract} \n Command" <|-- CookRecipeCommand
    "{abstract} \n Command" <|--- DeleteCommand
    "{abstract} \n Command" <|-- EditRecipeCommand
    "{abstract} \n Command" <|--- FindCommand
    "{abstract} \n Command" <|-- GoToCommand
    "{abstract} \n Command" <|--- ListCommand
    "{abstract} \n Command" <|-- UpdateCommand
    "{abstract} \n Command" <|--- ListCommandsCommand

    class CommandResult {
        + getFeedbackToUser(): String
    }

    class ScreenState
    CommandResult --> ScreenState
}



@enduml
