@startuml
skinparam classAttributeIconSize 0

package "model" {
    class Ingredient {
        -String ingredientName
        -int quantity
        +getIngredientName(): String
        +getQuantity(): int
        +setIngredientName(String name)
        +setQuantity(int quantity)
        +addQuantity(int quantity)
        +subtractQuantity(int quantity)
    }

    package "catalogue" {
        abstract class Catalogue<T> {
            -ArrayList<T> items
            +addItem(T item): CommandResult
            +deleteItem(T item): CommandResult
            +listItems(): CommandResult
            +getItems(): ArrayList<T>
            +updateItem(T oldItem, T newItem)
            +findItem(String query): CommandResult
            +findItem(String query, Function<T, String>): CommandResult
            +getItemByName(String name): T
            +getCatalogueContent(): String
            +getType(): String
        }

        class Inventory {
            +searchSimilarIngredient(Ingredient): ArrayList<Ingredient>
            +removeAllIngredients(): CommandResult
            +decreaseQuantity(Ingredient, Ingredient): CommandResult
            +getItemByName(String name): Ingredient
        }

        class Recipe {
            -String recipeName
            +getRecipeName(): String
            +updateItem(Ingredient): CommandResult
            +getItemByName(String name): Ingredient
        }

        class RecipeBook {
            +searchSimilarRecipe(Recipe): ArrayList<Recipe>
            +editItem(Recipe, Recipe): CommandResult
            +getItemByName(String name): Recipe
        }

        Catalogue <|-- Inventory
        Catalogue <|-- Recipe
        Catalogue <|-- RecipeBook
    }
}
@enduml