@startuml
package "storage" {
    class CatalogueContentManager {
        +loadInventory() : Inventory
        +loadRecipeBook() : RecipeBook
        +loadConsumablesCatalogue(Path, Supplier<T>) : <T extends Inventory> T
        +loadRawCatalogueContent(Path) : List<String>
        +saveToFile(Catalogue)

        -checkDirectoryExistence()
        -checkFileExistence(Path)
    }
}
@enduml
