@startuml

hide circle
skinparam classAttributeIconSize 0

class Ui {
    -scanner: Scanner
    +Ui()
    +Ui(InputStream inStream)
    +showInitMessage()
    +showDivider()
    +showScreenPrompt(ScreenState screen)
    -showWelcomeMessage()
    -showInventoryMessage()
    -showRecipeMessage()
    -showRecipeBookMessage()
    +showGoodbyeMessage()
    +getUserCommand(): String
    +showResultToUser(CommandResult result)
}

@enduml